<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

    <AssemblyTitle>JFlightShaker C.E</AssemblyTitle>
    <Product>JFlightShaker C.E</Product>
    <Version>0.5.0-beta.1</Version>
    <AssemblyVersion>0.5.0.0</AssemblyVersion>
    <FileVersion>0.5.0.0</FileVersion>
    <InformationalVersion>0.5.0-beta.1</InformationalVersion>
    <ApplicationIcon>Assets/JFlightCE-0.4.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="JFlightShaker.Tests/**/*.cs" />
    <Resource Include="Assets/JFlightCE-0.4.ico" />
    <Resource Include="Assets/JFlightCE-High.png" />
    <Resource Include="Assets/JFlightCE-Background.png" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
  </ItemGroup>

</Project>
